name: Submit a tool

description: Propose a tool or platform for the Event Tech Landscape

title: "Add: [Tool Name]"

labels: ["tool-submission"]

body:
  - type: input
    id: tool
    attributes:
      label: Tool name
      placeholder: Example Tool
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Official website
      placeholder: https://example.com
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: Category
      placeholder: Event Management Platforms
    validations:
      required: true
  - type: input
    id: focus
    attributes:
      label: Category focus
      placeholder: Brief focus statement
    validations:
      required: true
  - type: dropdown
    id: pricing
    attributes:
      label: Pricing model
      options:
        - Freemium
        - Usage-based
        - Subscription
        - Enterprise
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I confirmed the tool is active and publicly available
          required: true
        - label: I confirmed the official website link works
          required: true
